TITLE = 'COMPENDIUM GENERATOR'
DEFAULT_SELECTED_FILE = 'select a file in the file menu'
DEFAULT_SEARCH_CONCEPT = "type a concept to look for ..."
DEFAULT_MAIL = 'kavilac@gmail.com'
DEFAULT_TERM = 'Human Papillomavirus type 18 complete genome isolate'
FEATURE_NAME_OPTIONS = ['CDS']#['CDS','gene','source']
FEATURE_TAG_OPTIONS = ["gene product","gene","product"]#['gene','product','translation', 'codon_start','protein_id']
FEATURE_TAG_OPTIONS_PER_SEQ =["product"]#,"gene"]
DATABASES = [  'nucleotide','protein','structure', 'genome','cdd', 'gap','gene',
'genomeprj','homologene','ncbisearch','taxonomy']
FORMATS = ['gb','fasta']
ALIGNERS_OPTIONS = ["clustalW", "Muscle"]
FASTA_EXTENSION  = "fasta"
ALINGING_EXTENSION  = ".aln"
PHILO_EXTENSION = ".dnd"
IMAGE_EXTENSION = ".jpg"
DOT = '.'
FOLDER_POINTER = "./"
NEW_LINE = '\n'
EMPTY_STRING = ""
EMPTY_SEARCH = "Supplied id parameter is empty."
EMPTY_LIST = []
PREFIX_CONSENSUS = "_consensus_th"
FOLDER_SETTINGS_FILENAME = ".main_folder"
PRIMERS_INPUT_FILENAME = '_primers_input'
OS_LINUX = "linux"
OS_LINUX_SLASH = "/"
OS_WIN_SLASH = "\\"
CLUSTALW_LINUX_PATH = "../aligners/clustalw/linux/clustalw2"
CLUSTALW_MAC_PATH = "../aligners/clustalw/darwin/clustalw2"
IO_ERROR = '\nSorry! There is an IO error'
ERROR_EMPTY_FILE = 'Sorry! The file is empty. We can not work with it'
ERROR_FOLDER_NAME = 'Error no se selecciono ninguna carpeta'
ERROR_MAIL = '\nSorry! There is an error in the email writing'
ERROR_FOLDER_NAME = "\nSorry! The folder name can not be empty"
ERROR_FILE_NAME = "\nSorry! The file name can not be empty"
ERROR_RETMAX = '\nSorry! Retmax should be a number'
ERROR_FILTER_ENABLE = '\nSorry! You should check the filter checkbox'
ERROR_SELECTED_FILE = '\nSorry! You should select a file'
ERROR_TAGS_VALUES = '\nSorry! Tags values can not be empty'
ERROR_FILTERING = '\nSorry! We could not find tags values in your sequence data'
ERROR_SETTINGS = '\nSorry! There is a problem with your settings. Please check them.'
ERROR_PHILO = '\nPhilo tree Error'
ERROR_CONSENSUS = '\nConsensus sequence error'
ERROR_FILE_LIST = '\nSorry! There is no filename list'

LOAD_SETTINGS_MSJ = '\nLoading settings ...'
CLUSTALW_SETTINGS_MSJ = '\nGetting ClustalW path ...'
SELECTED_FILE_WARNING = '\nWarning! There is no selected file'
FOLDER_SETTINGS_MSJ = '\nYour Settings are:\n\nMain folder:\n'
AUTOMATIC_SETTINGS_MSJ = '\nThe automatic enable button is:'
DEFAULT_SETTINGS_MSJ = '\nThe default enable button is:'
WORKING_FOLDER_MSJ = '\nWorking folder:\n'
SAVING_CONSENSUS_MSJ = '\nSaving consensus...'
CLUSTAL_ALING_MSJ = '\n\nAligning with ClustalW...'
MUSCLE_ALING_MSJ = '\nAligning with Muscle...'
PHILO_MSJ = '\n\nGetting phylo tree ...'
ALIGN_DATA_MSJ = '\nGetting align data...'
CONSENSUS_MSJ = '\n\nGetting consensus sequence...'



INICIAL = 0
SIZE = '1200x600'
SEARCH_FRAME_SIZE = '900x150'
TOP_PANEL_MAINWINDOW_HEIGHT = 50
TOP_PANEL_TAB_HEIGHT = 50
CLUSTAL_PANEL_HEIGHT = 10
TOP_PANEL_SEARCH_FRAME_HEIGHT = 50
PANELS_EXPAND = 1
LBL_SELECTED_FILE_X = 100
LBL_SELECTED_FILE_Y = 16
MENU_TEAROFF = 0
INFORMER_HEIGHT = 41
INFORMER_WIGTH = 40
DEFAULT_TAB_INFORMERS_HEIGHT = 27
DEFAULT_TAB_INFORMERS_WIGTH = 125
ALIGN_INFORMER_HEIGHT = 30
ALIGN_INFORMERS_WIGTH = 125
TABS_WIDTH = 900
TABS_HEIGHT = 550
LEFT_PADDING = 10
TOP_PADDING = 0
RIGHT_PADDING = 10
BOTTOM_PADDING = 15
CHKBOX_OFF = 0
CHKBOX_ON = 1
INDEX_CLUSTALW = 0
INDEX_FILTER_TAB = 0
INDEX_ALIGNMENT_TAB = 1
INDEX_PRIMERS_TAB = 2
INDEX_BLAST_TAB = 3
INDEX_REPORTS = 4
BLANK_SPACE_X = 80
BLANK_SPACE_Y = 20
DEFAULT_TXTBOX_HEIGHT = 1
TXTBOX_MAIL_WIGTH = 54
TXTBOX_TERM_WIGTH = 110
TXTBOX_RETMAX_WIGTH = 10
TXTBOX_FILENAME_WIGTH = 30
TXTBOX_FOLDER_WIGTH = 30
TXTBOX_FEATURE_NAME_WIGTH = 40
TXTBOX_FEATURE_TAG_WIGTH = 40
TXTBOX_TAG_VALUES_WIGTH = 30
TXTBOX_THRESHOLD_WIGTH = 10
TXTBOX_PRIMER_SIZE_WIGTH = 10
TXTBOX_THRESHOLD_WIGTH = 10




