TITLE = 'COMPENDIUM GENERATOR'
IO_ERROR = 'Sorry! There is an IO error'
DEFAULT_SELECTED_FILE = 'select a file in the file menu'
DEFAULT_SEARCH_CONCEPT = "type a concept to look for ..."
DEFAULT_MAIL = 'Ex. kavilac@gmail.com'
DEFAULT_TERM = 'Ex. Human Papillomavirus type 18 complete genome isolate'
DATABASES = [  'nucleotide','protein','structure', 'genome','cdd', 'gap','gene',
'genomeprj','homologene','ncbisearch','taxonomy']
FORMATS = ['gb','fasta']

SIZE = '1200x600'
TOP_PANEL_MAINWINDOW_HEIGHT = 50
TOP_PANEL_SEARCH_TAB_HEIGHT = 100
PANELS_EXPAND = 1
LBL_SELECTED_FILE_X = 100
LBL_SELECTED_FILE_Y = 16
MENU_TEAROFF = 0
INFORMER_HEIGHT = 41
INFORMER_WIGTH = 40
DEFAULT_TAB_INFORMERS_HEIGHT = 15
DEFAULT_TAB_INFORMERS_WIGTH = 125
TABS_WIDTH = 900
TABS_HEIGHT = 550
LEFT_PADDING = 10
TOP_PADDING = 0
RIGHT_PADDING = 10
BOTTOM_PADDING = 15
INDEX_SEARCH_TAB = 0
INDEX_ALIGNMENT_TAB = 1
INDEX_PRIMERS_TAB = 2
INDEX_BLAST_TAB = 3
INDEX_REPORTS = 4
BLANK_SPACE_X = 80
DEFAULT_TXTBOX_HEIGHT = 1
TXTBOX_MAIL_WIGTH = 54
TXTBOX_TERM_WIGTH = 110
TXTBOX_RETMAX_WIGTH = 10
TXTBOX_FILENAME_WIGTH = 30
TXTBOX_FOLDER_WIGTH = 30








