DEFAULT_RETMAX = 20; # Total number of UID from the retrieved set to be shown
CONSENSUS_THRESHOLD = 0.7

EXP_REG_RNA = '[A|C|G|T]{4,}|[a|c|g|t]{4,}'#{4,}filtra que la longitud de la cadena sea mayor a 4 caracteres
SEQUENCE_ID = "SEQUENCE_ID"
SEQUENCE_TEMPLATE = "SEQUENCE_TEMPLATE"
SEQUENCE_TARGET = "SEQUENCE_TARGET"
PRIMER_PRODUCT_SIZE_RANGE = "PRIMER_PRODUCT_SIZE_RANGE"
P3_FILE_FLAG = "P3_FILE_FLAG=1"
EQUAL_SIGN = "="
NEW_LINE = '\n'
SEPARATOR = '------------------------------------------------'
DEFAULT_PRODUCT_SIZE = "100-300"
PRIMERS_FOLDER = "/primers/"
LEFT_PRIMERS_EXT = ".for"
RIGHT_PRIMERS_EXT = ".rev"
INTERNAL_PRIMERS_EXT = ".int"
BLAST_PROGRAM = "blastn"
BLAST_DATABASE = "nt"
BLAST_OUT_FORMAT = "text"
ERROR_PRIMERS = '\nPrimers Error!'
IO_ERROR = '\nSorry! There is an IO error'





##PRIMERS PREFIX
PREFIX_PRIMER_NUMBER = "PRIMER_NUM_RETURN" #v/
#PREFIX_MAX_SELF_COMPLEMENTARY = PRIMER_PAIR_MAX_COMPL_END
PREFIX_SALT_MONOVALENT = "PRIMER_SALT_MONOVALENT"#v/
PREFIX_PRODUCT_RANGE = "PRIMER_PRODUCT_SIZE_RANGE" #v/
#PREFIX_MAX_3_STABILITY = "PRIMER_MAX_END_STABILITY "
#PREFIX_MAX_3_SELF_COMPLEMENTARY =
PREFIX_PRIMER_MIN_SIZE = "PRIMER_MIN_SIZE"#v/
PREFIX_PRIMER_OPT_SIZE = "PRIMER_OPT_SIZE"#v/
PREFIX_PRIMER_MAX_SIZE = "PRIMER_MAX_SIZE"#v/
PREFIX_PRIMER_MIN_TM = "PRIMER_MIN_TM"#v/
PREFIX_PRIMER_OPT_TM = "PRIMER_OPT_TM"#v/
PREFIX_PRIMER_MAX_TM = "PRIMER_MAX_TM"#v/
PREFIX_PRIMER_MIN_GC = "PRIMER_MIN_GC"
PREFIX_PRIMER_MAX_GC = "PRIMER_MAX_GC"
PREFIX_PRIMER_SEQ_TARGET = "SEQUENCE_TARGET" #v/
PREFIX_MAX_POLY_X = "PRIMER_MAX_POLY_X"
PREFIX_SEQUENCE_ID = "SEQUENCE_ID"  #v/
PREFIX_SEQUENCE_TEMPLATE = "SEQUENCE_TEMPLATE" #v/
PREFIX_P3_FILE_FLAG = "P3_FILE_FLAG" #v/

##PRIMER DEFAULT VALUES
PRIMER_NUMBER = 5
#MAX_SELF_COMPLEMENTARY = DUDA
SALT_MONOVALENT = 50.0
PRODUCT_RANGE = "100-300"
#MAX_3_STABILITY = DUDA
#MAX_3_SELF_COMPLEMENTARY = DUDA
PRIMER_MIN_SIZE = 15
PRIMER_OPT_SIZE = 18
PRIMER_MAX_SIZE = 21
PRIMER_MIN_TM = 57.0
PRIMER_OPT_TM = 60.0
PRIMER_MAX_TM = 63.0
PRIMER_MIN_GC = 20.0
PRIMER_MAX_GC = 80.0
PRIMER_SEQ_TARGET = "37,21"
MAX_POLY_X = 5
P3_FILE_FLAG_VALUE = 1








